export const STATUS_APPOINTMENT = {
    PENDIENTE: 'PENDIENTE',
    CONFIRMADA: 'CONFIRMADA',
    CANCELADA: 'CANCELADA',
    REPROGRAMADA: 'REPROGRAMADA',
    COMPLETADA: 'COMPLETADA'
} as const;

export type STATUS_APPOINTMENT = typeof STATUS_APPOINTMENT[keyof typeof STATUS_APPOINTMENT];